# Default configuration for basic-service

app:
  name: basic-service
  version: 1.0.0
  port: 8080
  logLevel: info
  
api:
  prefix: /api/v1
  timeout: 30000
  
health:
  enabled: true
  
# Add your service-specific configuration below
# database:
#   host: localhost
#   port: 5432
#   name: mydb
#   
# cache:
#   host: localhost
#   port: 6379
